SELECT * FROM MENUS;
SELECT * FROM NOTICES;
UPDATE BASKETS SET AMOUNT=1 WHERE MID=1;
SELECT * FROM MEMBERS WHERE MID IN ('1','wlslwlsl','2');
SELECT * FROM STORES;
SELECT * FROM OWNERS;
SELECT * FROM MENUS;
SELECT * FROM BASKETS;
SELECT * FROM ORDERS;
SELECT * FROM ORDERS ORDER BY TO_NUMBER(ORDERSEQ) DESC;
SELECT * FROM COMMENTS ORDER BY TO_NUMBER(COSEQ) DESC;
SELECT * FROM NCOMMENTS;
SELECT * FROM MEMBERS;
COMMIT;

DELETE FROM COMMENTS;
DELETE FROM BASKETS;
DELETE FROM CHATS;
DELETE FROM MEMBERS;
DELETE FROM MENUS;
DELETE FROM NCOMMENTS;
DELETE FROM NCOMMENTSREC;
DELETE FROM NOTICES;
DELETE FROM NOTICESREC;
DELETE FROM ORDERS;
DELETE FROM SEARCH;
DELETE FROM STORES;
ROLLBACK;
COMMIT;

DELETE FROM CONFIRMATION;
SELECT S.STORENAME, S.ADDRESS,S.PHONENUMBER FROM BASKETS B JOIN MENUS M ON B.MSEQ=M.MSEQ JOIN STORES S ON M.SSEQ=S.SEQ WHERE B.MID='1' GROUP BY  S.STORENAME, S.ADDRESS,S.PHONENUMBER ;
UPDATE ORDERS SET ORDERMID='vyduwls' WHERE ORDERMID='admin';

SELECT MSEQ,CATEGORY,MENUNAME,ENGMENUNAME,MENUINFO,SCORE,PRICE,IMG,M.SSEQ AS SSEQ FROM MENUS M JOIN STORES S ON S.SEQ=M.SSEQ WHERE M.SSEQ='1';

ALTER TABLE MENUS DROP COLUMN STORENAME;
ALTER TABLE COMMENTS ADD IMAGES VARCHAR2(1000);
INSERT INTO COMMENTS (CSEQ,COSEQ,CMID,CONTENT) VALUES((SELECT NVL(MAX(TO_NUMBER(CSEQ)),0)+1 FROM COMMENTS),'41','123','zzzzzzzzzzzzzzzz');

SELECT M.MSEQ,M.CATEGORY,M.MENUNAME,M.PRICE,M.IMG,M.MSEQ,S.STORENAME FROM MENUS M JOIN STORES S ON S.SEQ=M.SSEQ WHERE M.SSEQ='1';

SELECT M.MSEQ,M.CATEGORY,M.MENUNAME,M.PRICE,M.IMG,M.MSEQ,S.STORENAME FROM MENUS M JOIN STORES S ON S.SEQ=M.SSEQ WHERE M.SSEQ='1';
DELETE FROM COMMENTS;
DELETE FROM BASKETS;

COMMIT;
ALTER TABLE BASKETS MODIFY (REQUIREMENTS VARCHAR2(50) DEFAULT '없음' NOT NULL);
UPDATE MENUS SET SSEQ='1' ;
INSERT INTO ORDERS VALUES((SELECT NVL(MAX(TO_NUMBER(ORDERSEQ)),0)+1 FROM ORDERS),'vyduwls','136',10,'2017-06-20 10:00','01049675242','많이주세열',54000,'17/06/20','확인완료');


SELECT * FROM (SELECT ROWNUM RN, N.* FROM (SELECT * FROM BASKETS  WHERE MID='1' ORDER BY TO_NUMBER(BASKETSEQ) DESC) N) WHERE RN BETWEEN ? AND ?;

ALTER TABLE ORDERS ADD STATEMENT VARCHAR(50) DEFAULT '주문완료';
ROLLBACK;
DELETE FROM BASKETS WHERE BASKETSEQ IN (2,1);

SELECT ROWNUM , N.* FROM (SELECT * FROM BASKETS  WHERE MID='1' ORDER BY TO_NUMBER(BASKETSEQ) DESC) N WHERE ROWNUM BETWEEN 21 AND 30 ;
SELECT * FROM (SELECT ROWNUM RN, N.* FROM (SELECT * FROM BASKETS WHERE "+field+" LIKE ? ORDER BY TO_NUMBER(SEQ) DESC) N) WHERE RN BETWEEN ? AND ?;
INSERT INTO STORES VALUES ('SEQ7','1','02-789-7412','STORENAME1','서울시 강남구','010-7895-4566','../img/search/mac.png',SYSDATE);

DROP TABLE BASKETS;
DROP TABLE MENUS;
DROP TABLE ORDERS;
DROP TABLE COMMENTS;
COMMIT;
DELETE BASKETS WHERE MSEQ='1';
INSERT INTO BASKETS (BASKETSEQ,MID,MSEQ,AMOUNT,TIME,PHONENUMBER,REQUIREMENTS) VALUES((SELECT NVL(MAX(TO_NUMBER(BASKETSEQ)),0)+1 FROM BASKETS),'1','1','0','0','0','0');
INSERT INTO MEMBERS 
VALUES('MAC','123','MAC','AAA@NAVER.COM','222-10-22','010-7777-8888','1');
INSERT INTO OWNERS 
VALUES('STORENAME1','서울시은평구불광동','MAC');
INSERT INTO MENUS (MSEQ, STORENAME, CATEGORY, MENUNAME, ENGMENUNAME, MENUINFO, SCORE, PRICE, IMG) VALUES (1.0,'STORENAME1','Burger','골든 에그 치즈버거','Golden Egg Cheeseburger','짭쪼름한 간장베이스와 
바삭함을 살려주는 버터밀크 파우더를 더해 튀겨 낸 
두툼한 통 닭다리살이 버거 속으로!',2.0,5400.0,'GoldenEggCheeseburger.png');
INSERT INTO MENUS (MSEQ, STORENAME, CATEGORY, MENUNAME, ENGMENUNAME, MENUINFO, SCORE, PRICE, IMG) VALUES (2.0,'STORENAME1','Burger','그릴드 머쉬룸 버거','Grilled Mushroom Burger','짭쪼름한 간장베이스와 
바삭함을 살려주는 버터밀크 파우더를 더해 튀겨 낸 
두툼한 통 닭다리살이 버거 속으로!',2.0,5400.0,'CrispyOrientalChickenBurger.png');
INSERT INTO MENUS (MSEQ, STORENAME, CATEGORY, MENUNAME, ENGMENUNAME, MENUINFO, SCORE, PRICE, IMG) VALUES (3.0,'STORENAME1','Burger','크리스피 오리엔탈 치킨버거','Crispy Oriental Chicken Burger','짭쪼름한 간장베이스와 
바삭함을 살려주는 버터밀크 파우더를 더해 튀겨 낸 
두툼한 통 닭다리살이 버거 속으로!',2.0,5400.0,'CrispyOrientalChickenBurger.png');
--행 4
INSERT INTO MENUS (MSEQ, STORENAME, CATEGORY, MENUNAME, ENGMENUNAME, MENUINFO, SCORE, PRICE, IMG) VALUES (4.0,'STORENAME1','Burger','빅맥','Big Mac','100% 순 쇠고기 패티 두 장에 빅맥®만의 특별한 소스.
입안에서 살살 녹는 치즈와 신선한 양상추, 양파, 그리고 피클까지. 
40년 넘게 전 세계인의 입맛을 사로 잡은 버거의 대명사.',1.0,4400.0,'BigMac.png');
--행 5
INSERT INTO MENUS (MSEQ, STORENAME, CATEGORY, MENUNAME, ENGMENUNAME, MENUINFO, SCORE, PRICE, IMG) VALUES (5.0,'STORENAME1','Burger','메가맥','메가맥Mega Mac','STORENAME1 대표 제품, 빅맥®을 메가 사이즈로 만나보세요.
100% 순 쇠고기 패티 네 장에 빅맥®만의 특별한 소스.
입안에서 살살 녹는 치즈와 신선한 양상추, 양파, 그리고 피클까지-',4.0,5500.0,'MegaMac.png');
--행 6
INSERT INTO MENUS (MSEQ, STORENAME, CATEGORY, MENUNAME, ENGMENUNAME, MENUINFO, SCORE, PRICE, IMG) VALUES (6.0,'STORENAME1','Burger','상하이 버거',' Shanghai Burger','매콤한 시즈닝을 입힌 100% 닭가슴 통살 위에
아삭아삭한 양상추와 신선한 토마토~
겉은 바삭, 속은 부드러운 치킨 패티의 매콤함으로
입맛도 기분도 화끈하게!',5.0,4400.0,'ShanghaiBurger.png');
--행 7
INSERT INTO MENUS (MSEQ, STORENAME, CATEGORY, MENUNAME, ENGMENUNAME, MENUINFO, SCORE, PRICE, IMG) VALUES (7.0,'STORENAME1','Burger','1955','1955','113g 두툼한 쇠고기 패티와 그릴 어니언!
오리지널의 맛을 살리다',4.0,5400.0,'1955.png');
--행 8
INSERT INTO MENUS (MSEQ, STORENAME, CATEGORY, MENUNAME, ENGMENUNAME, MENUINFO, SCORE, PRICE, IMG) VALUES (8.0,'STORENAME1','Burger','더블 1955','Double 1955 ','113g 두툼한 쇠고기 패티와 그릴 어니언, 
오리지널의 맛을 두 배 더 푸짐하게 즐겨보세요!',4.0,5800.0,'Double1955 .png');
--행 9
INSERT INTO MENUS (MSEQ, STORENAME, CATEGORY, MENUNAME, ENGMENUNAME, MENUINFO, SCORE, PRICE, IMG) VALUES (9.0,'STORENAME1','Burger','쿼터파운더 치즈','치즈Quarter Poundersub','쿼터파운더라는 이름에서 알 수 있듯이 두 배 이상 커진
1/4파운드(113그램) 비프와 부드러운 치즈 두 장의 환상궁합!
두툼한 비프와 신선한 치즈의 풍부한 맛으로 
세계적으로 사랑받고 있는 STORENAME1의 대표적인 프리미엄 버거',3.0,5400.0,'QuarterPounderwithCheese.png');
--행 10
INSERT INTO MENUS (MSEQ, STORENAME, CATEGORY, MENUNAME, ENGMENUNAME, MENUINFO, SCORE, PRICE, IMG) VALUES (10.0,'STORENAME1','MORNING','더블 쿼터파운더™ 치즈','치즈Double Quarter Poundersub','좋아하는건 더 많이 즐기시라고, 두 배 이상 커진 1/4 파운드
비프 패티가 두 장 (226그램)! 육즙이 풍부한 고기 맛을
그대로 살린 100% 순 쇠고기 패티 두 장과 치즈 두 장이
입안 가득 완벽하게 조화되는 놀라운 맛',5.0,4900.0,'DoubleQuarterPounderwithCheese.png');
--행 11
INSERT INTO MENUS (MSEQ, STORENAME, CATEGORY, MENUNAME, ENGMENUNAME, MENUINFO, SCORE, PRICE, IMG) VALUES (11.0,'STORENAME1','MORNING','슈슈버거','Supreme Shrimp Burger','슈프림한 슈림프, 슈슈버거!
통새우 속살이 그대로 살아있는 패티에
매콤 달콤한 소스까지!',4.0,4400.0,'SupremeShrimpBurger.png');
--행 12
INSERT INTO MENUS (MSEQ, STORENAME, CATEGORY, MENUNAME, ENGMENUNAME, MENUINFO, SCORE, PRICE, IMG) VALUES (12.0,'STORENAME1','MORNING','슈비버거','Shrimp Beef Burger','슈림프와 비프의 찰떡궁합! 슈비버거!
탱글탱글한 통새우 속살 패티에
비프 패티까지 꽉 채워 든든하게!',2.0,5400.0,'ShrimpBeefBurger.png');
--행 13
INSERT INTO MENUS (MSEQ, STORENAME, CATEGORY, MENUNAME, ENGMENUNAME, MENUINFO, SCORE, PRICE, IMG) VALUES (13.0,'STORENAME1','MORNING','베이컨 토마토 디럭스','Bacon Tomato Deluxesub','두 장의 100% 순 쇠고기 패티에 그릴에 구워 더욱 고소한
1장의 베이컨을 얹고, 신선한 토마토와 양상추,
매콤달콤한 스위트 칠리 소스, 치즈, 마요네즈를 더해
더욱 풍부하고 신선한 맛의 프리미엄 버거.',1.0,5000.0,'BaconTomatoDeluxesub.png');
--행 14
INSERT INTO MENUS (MSEQ, STORENAME, CATEGORY, MENUNAME, ENGMENUNAME, MENUINFO, SCORE, PRICE, IMG) VALUES (14.0,'STORENAME1','SET','토마토 치즈버거','Tomato Cheeseburger','고소한 치즈버거에 
신선한 토마토와 양상추가 더해져 
더욱 신선한 행복의 나라 메뉴 신제품',4.0,5100.0,'TomatoCheeseburger.png');
--행 15
INSERT INTO MENUS (MSEQ, STORENAME, CATEGORY, MENUNAME, ENGMENUNAME, MENUINFO, SCORE, PRICE, IMG) VALUES (15.0,'STORENAME1','SET','불고기 버거','Bulgogi Burger','한국인의 입맛에 딱 맞는 불고기 소스에 잘 재운 패티와
고소한 마요네즈, 신선한 양상추의 맛있는 조합.',5.0,5200.0,'BulgogiBurger.png');
--행 16
INSERT INTO MENUS (MSEQ, STORENAME, CATEGORY, MENUNAME, ENGMENUNAME, MENUINFO, SCORE, PRICE, IMG) VALUES (16.0,'STORENAME1','SET','더블 불고기 버거','Double Bulgogi Burger','진한 불고기 소스의 패티가 두 장!
여기에 고소한 치즈와 마요네즈, 
신선한 양상추를 곁들인 깊고 풍부한 맛.',5.0,4400.0,'DoubleBulgogiBurger.png');
--행 17
INSERT INTO MENUS (MSEQ, STORENAME, CATEGORY, MENUNAME, ENGMENUNAME, MENUINFO, SCORE, PRICE, IMG) VALUES (17.0,'STORENAME1','SET','치킨 버거','Chicken Burger','담백한 치킨 패티에 신선한 양상추와 
고소한 마요네즈가 만난 부드러운 맛을 느껴보세요.',4.0,3000.0,'ChickenBurger.png');
--행 18
INSERT INTO MENUS (MSEQ, STORENAME, CATEGORY, MENUNAME, ENGMENUNAME, MENUINFO, SCORE, PRICE, IMG) VALUES (18.0,'STORENAME1','SET','치즈버거','Cheeseburger','고소하고 부드러운 치즈와 100% 순 쇠고기 패티,
STORENAME1만의 심플한 클래식 치즈버거.',3.0,2900.0,'Cheeseburger.png');
--행 19
INSERT INTO MENUS (MSEQ, STORENAME, CATEGORY, MENUNAME, ENGMENUNAME, MENUINFO, SCORE, PRICE, IMG) VALUES (19.0,'STORENAME1','SET','햄버거','Hamburger','100% 순 쇠고기 패티에 상큼한 피클과 양파,
기본에 충실한 STORENAME1 햄버거.',2.0,2000.0,'Hamburger.png');